import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from "@clerk/themes";
import { Geist, Geist_Mono, Inter, Poppins, Space_Grotesk, Roboto_Mono, Outfit, Dosis, Roboto, Noto_Sans, Saira, Audiowide, Source_Code_Pro } from "next/font/google";

import "./globals.css";

// Fonts (Modify weights as needed)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const code = Source_Code_Pro({subsets: ["latin"], variable: "--font-code", weight: ["400", "300"]})
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const poppins = Poppins({ subsets: ["latin"], weight: ["400","600","700"], variable: "--font-poppins" });
const spaceGrotesk = Space_Grotesk({ subsets: ["latin"], variable: "--font-space-grotesk" });
const robotoMono = Roboto_Mono({ subsets: ["latin"], variable: "--font-roboto-mono" });
const outfit = Outfit({ subsets: ["latin"], variable: "--font-outfit", weight: ["100", "300", "400"]});
const audiowide = Audiowide({ subsets: ["latin"], weight: ["400"], variable: "--font-autowide"});

const dosisScript = Dosis({
  variable: "--font-dosis-script",
  subsets: ["latin"],
});

const robotoScript = Roboto({ 
  variable: "--font-roboto-script",
  subsets: ["latin"],
});

const sairaScript = Saira({ 
  variable: "--font-saira-script",
  subsets: ["latin"],
});

const notoScript = Noto_Sans({
  variable: "--font-noto-script",
  subsets: ["latin"],
  weight: ["200", "300", "500"]
})

// === \\

export const metadata: Metadata = {
  title: "Hood Lens",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <ClerkProvider afterSignInUrl={"/dashboard?page=general"} afterSignOutUrl={"/"} afterSignUpUrl={"/auth/login"} appearance={{ theme: dark }}
    publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} 
        ${poppins.variable} ${spaceGrotesk.variable} ${robotoMono.variable} ${outfit.variable}
        ${dosisScript.variable} ${robotoScript.variable} ${notoScript.variable} ${sairaScript.variable}  
        ${audiowide.variable} ${code.variable} antialiased`}
      >
        {children}
      </body>
    </html>
    </ClerkProvider>
    </>
  );
}
